<Project Sdk="Microsoft.NET.Sdk">

  <Import Project=".\..\CommonAssemblyInfo.props" />

  <PropertyGroup>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <!-- Create the configuration to buid various versions of Revit -->
    <Configurations>Debug;2026;2025;2024;2023;2022;2021;2020;2019</Configurations>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Platforms>x64</Platforms>
    <NuGetAudit>false</NuGetAudit>
    <BuildInParallel>false</BuildInParallel>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>


  <!-- If the configuration is a Revit version,
    we use this configuration as a variable 
    for the rest of the csproj -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <RevitVersion>$(Configuration)</RevitVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <!-- We can only debug just ONE addin version.
         Instead of building all versions above,
         we just put ONE version below and switch to 'Debug' configuration
      -->
    <RevitVersion>2026</RevitVersion>
    <StartAction>Program</StartAction>
    <StartProgram>$(ProgramW6432)\Autodesk\Revit Preview Release\Revit.exe</StartProgram>
  </PropertyGroup>

  <Choose>
    <When Condition=" '$(RevitVersion)'=='2025'  Or '$(RevitVersion)'=='2026'">
      <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
      </PropertyGroup>
    </Otherwise>
  </Choose>

  <!-- Get the RevitAPI.dll, RevitAPIUI.dll, AdWindows.dll and UIFramework.dll -->
  <Choose>
    <When Condition="'$(RevitVersion)'=='2026'">
      <ItemGroup>
        <Reference Include="RevitAPI">
          <HintPath>$(PROGRAMFILES)\Autodesk\Revit Preview Release\RevitAPI.dll</HintPath>
          <Private>False</Private>
        </Reference>
        <Reference Include="RevitAPIUI">
          <HintPath>$(PROGRAMFILES)\Autodesk\Revit Preview Release\RevitAPIUI.dll</HintPath>
          <Private>False</Private>
        </Reference>
      </ItemGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <RevitNugetVersion>$(RevitVersion).*</RevitNugetVersion>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="$(RevitNugetVersion)" IncludeAssets="build; compile" PrivateAssets="All" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <!-- Release -->
  <PropertyGroup Condition="!$(Configuration.Contains('Debug'))">
    <Optimize>true</Optimize>
    <OutputPath>bin\$(RevitVersion)\</OutputPath>
    <DefineConstants>REVIT$(RevitVersion)</DefineConstants>
    <NoWarn>MSB3052</NoWarn>
    <DebugType>None</DebugType>
  </PropertyGroup>

  <!-- Debug -->
  <PropertyGroup Condition="$(Configuration.Contains('Debug'))">
    <DebugSymbols>true</DebugSymbols>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE;REVIT$(RevitVersion)</DefineConstants>
    <DebugType>Full</DebugType>
  </PropertyGroup>


  <ItemGroup>
    <EmbeddedResource Include="Resources\floor-finishes-large.png" />
    <EmbeddedResource Include="Resources\floor-finishes-small.png" />
    <EmbeddedResource Include="Resources\room-finishes-large.png" />
    <EmbeddedResource Include="Resources\room-finishes-small.png" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="PackageContents.xml" />
  </ItemGroup>

  <Target Name="AfterClean">
    <Delete Files="$(AppData)\Autodesk\REVIT\Addins\2016\RoomFinishes.addin" />
    <Delete Files="$(AppData)\Autodesk\REVIT\Addins\2016\RoomFinishes.dll" />
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell -ExecutionPolicy Unrestricted $(ProjectDir)PostBuild.ps1 -RevitVersion $(RevitVersion) -TargetName $(TargetName) -ProjectDir $(ProjectDir) -TargetPath $(TargetPath) -TargetDir $(TargetDir)" />
  </Target>
</Project>