//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomFinishes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomFinishes.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor height.
        /// </summary>
        internal static string floorFinishes_groupboxName {
            get {
                return ResourceManager.GetString("floorFinishes_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From value.
        /// </summary>
        internal static string floorFinishes_height_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From parameter.
        /// </summary>
        internal static string floorFinishes_height_param_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an elevation value for the floor :.
        /// </summary>
        internal static string floorFinishes_heightValueError {
            get {
                return ResourceManager.GetString("floorFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no room in the current model.
        /// </summary>
        internal static string floorFinishes_noRoomError {
            get {
                return ResourceManager.GetString("floorFinishes_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Finishes.
        /// </summary>
        internal static string floorFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("floorFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a floor type :.
        /// </summary>
        internal static string floorFinishes_select_floor_label {
            get {
                return ResourceManager.GetString("floorFinishes_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create floor finishes.
        /// </summary>
        internal static string floorFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("floorFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create finishing floor.
        /// </summary>
        internal static string floorFinishes_toolTip {
            get {
                return ResourceManager.GetString("floorFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor finish.
        /// </summary>
        internal static string floorFinishes_transactionName {
            get {
                return ResourceManager.GetString("floorFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is failed for unexpected reason..
        /// </summary>
        internal static string floorFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("floorFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Elevation Max.
        /// </summary>
        internal static string levelTag_bottom_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Elevation Min.
        /// </summary>
        internal static string levelTag_bottom_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_bottom_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation.
        /// </summary>
        internal static string levelTag_parameter_group {
            get {
                return ResourceManager.GetString("levelTag_parameter_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Elevation Max.
        /// </summary>
        internal static string levelTag_top_elevation_max {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Elevation Min.
        /// </summary>
        internal static string levelTag_top_elevation_min {
            get {
                return ResourceManager.GetString("levelTag_top_elevation_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rooms in current view.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirting board height:.
        /// </summary>
        internal static string roomFinishes_board_height_label {
            get {
                return ResourceManager.GetString("roomFinishes_board_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skirting
        ///Board.
        /// </summary>
        internal static string roomFinishes_button_name {
            get {
                return ResourceManager.GetString("roomFinishes_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a height value for the skirting board :.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join geometry.
        /// </summary>
        internal static string roomFinishes_joinWalls {
            get {
                return ResourceManager.GetString("roomFinishes_joinWalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Finishes.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a wall type for a skirting board :.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only selected rooms.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Rooms.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create skirting board.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create skirting boards.
        /// </summary>
        internal static string roomFinishes_toolTip {
            get {
                return ResourceManager.GetString("roomFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating boundary finishes.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command is failed for unexpected reason..
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function will not work on wall type with a vertically compound structure..
        /// </summary>
        internal static string roomFinishes_verticallyCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticallyCompoundError", resourceCulture);
            }
        }
    }
}
