//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomFinishes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomFinishes.Resources.fr", typeof(fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elévation du sol.
        /// </summary>
        internal static string floorFinishes_groupboxName {
            get {
                return ResourceManager.GetString("floorFinishes_groupboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        internal static string floorFinishes_height_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametre.
        /// </summary>
        internal static string floorFinishes_height_param_label {
            get {
                return ResourceManager.GetString("floorFinishes_height_param_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer une élévation pour le sol.
        /// </summary>
        internal static string floorFinishes_heightValueError {
            get {
                return ResourceManager.GetString("floorFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a pas de pièce dans le modèle actuel.
        /// </summary>
        internal static string floorFinishes_noRoomError {
            get {
                return ResourceManager.GetString("floorFinishes_noRoomError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finitions de sol.
        /// </summary>
        internal static string floorFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("floorFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner un type de sol.
        /// </summary>
        internal static string floorFinishes_select_floor_label {
            get {
                return ResourceManager.GetString("floorFinishes_select_floor_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer des finitions de sol.
        /// </summary>
        internal static string floorFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("floorFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer des finitions de sol.
        /// </summary>
        internal static string floorFinishes_toolTip {
            get {
                return ResourceManager.GetString("floorFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finition de sol.
        /// </summary>
        internal static string floorFinishes_transactionName {
            get {
                return ResourceManager.GetString("floorFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande a échouée pour une raison inconnue.
        /// </summary>
        internal static string floorFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("floorFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les pièces de la vue.
        /// </summary>
        internal static string roomFinishes_all_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_all_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauteur de la plinthe.
        /// </summary>
        internal static string roomFinishes_board_height_label {
            get {
                return ResourceManager.GetString("roomFinishes_board_height_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plinthes.
        /// </summary>
        internal static string roomFinishes_button_name {
            get {
                return ResourceManager.GetString("roomFinishes_button_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string roomFinishes_Cancel_Button {
            get {
                return ResourceManager.GetString("roomFinishes_Cancel_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer une valeur de hauteur de la plinthe :.
        /// </summary>
        internal static string roomFinishes_heightValueError {
            get {
                return ResourceManager.GetString("roomFinishes_heightValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string roomFinishes_OK_Button {
            get {
                return ResourceManager.GetString("roomFinishes_OK_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finitions de pièces.
        /// </summary>
        internal static string roomFinishes_ribbon_panel_name {
            get {
                return ResourceManager.GetString("roomFinishes_ribbon_panel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner un type de mur pour la plinthe :.
        /// </summary>
        internal static string roomFinishes_select_wall_label {
            get {
                return ResourceManager.GetString("roomFinishes_select_wall_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniquement les pièces selectionnées.
        /// </summary>
        internal static string roomFinishes_selected_rooms_radio {
            get {
                return ResourceManager.GetString("roomFinishes_selected_rooms_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectionner les pieces.
        /// </summary>
        internal static string roomFinishes_SelectRooms {
            get {
                return ResourceManager.GetString("roomFinishes_SelectRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer des plinthes.
        /// </summary>
        internal static string roomFinishes_TaskDialogName {
            get {
                return ResourceManager.GetString("roomFinishes_TaskDialogName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer les finitions des pièces.
        /// </summary>
        internal static string roomFinishes_toolTip {
            get {
                return ResourceManager.GetString("roomFinishes_toolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer les plinthes.
        /// </summary>
        internal static string roomFinishes_transactionName {
            get {
                return ResourceManager.GetString("roomFinishes_transactionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La commande a échouée pour une raison inconnue.
        /// </summary>
        internal static string roomFinishes_unexpectedError {
            get {
                return ResourceManager.GetString("roomFinishes_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette commande ne fonctionne pas sur un mur divisé verticalement.
        /// </summary>
        internal static string roomFinishes_verticallyCompoundError {
            get {
                return ResourceManager.GetString("roomFinishes_verticallyCompoundError", resourceCulture);
            }
        }
    }
}
